image:
  file: .gitpod.Dockerfile
tasks:
  - init: yarn install
    command: yarn build && pip3 install platformio && node server/server.js
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
