const airSensor = [
  {
    name: 'USE_MHZ19',
    value: false,
    show: true,
    description: 'stepFeaturesMHZ19',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'air',
  },
  {
    name: 'USE_SENSEAIR',
    value: false,
    show: true,
    description: 'stepFeaturesSENSEAIR',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'air',
  },
  {
    name: 'USE_PMS5003',
    value: false,
    show: true,
    description: 'stepFeaturesPMS5003',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'air',
  },
  {
    name: 'USE_MGS',
    value: false,
    show: true,
    description: 'stepFeaturesMGS',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'air',
  },
  {
    name: 'USE_NOVA_SDS',
    value: false,
    show: true,
    description: 'stepFeaturesNOVA_SDS',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'air',
  },
  {
    name: 'USE_SGP30',
    value: false,
    show: true,
    description: 'stepFeaturesSGP30',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'air',
  },
  {
    name: 'USE_CCS811',
    value: false,
    show: true,
    description: 'stepFeaturesCCS811',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'air',
  },
  {
    name: 'USE_SCD30',
    value: false,
    show: true,
    description: 'stepFeaturesSCD30',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'air',
  },
  {
    name: 'USE_SPS30',
    value: false,
    show: true,
    description: 'stepFeaturesSPS30',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'air',
  },
  {
    name: 'USE_HPMA',
    value: false,
    show: true,
    description: 'stepFeaturesHPMA',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'air',
  },
  {
    name: 'USE_IAQ',
    value: false,
    show: true,
    description: 'stepFeaturesIAQ',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'air',
  },
];

export default airSensor;
