const energySensors = [
  {
    name: 'USE_HLW8012',
    value: false,
    show: true,
    description: 'stepFeaturesHLW8012',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_CSE7766',
    value: false,
    show: true,
    description: 'stepFeaturesCSE7766',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_PZEM004T',
    value: false,
    show: true,
    description: 'stepFeaturesPZEM004T',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_MCP39F501',
    value: false,
    show: true,
    description: 'stepFeaturesMCP39F501',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_PZEM_AC',
    value: false,
    show: true,
    description: 'stepFeaturesPZEM_AC',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_PZEM_DC',
    value: false,
    show: true,
    description: 'stepFeaturesPZEM_DC',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_ADE7953',
    value: false,
    show: true,
    description: 'stepFeaturesADE7953',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_SDM120',
    value: false,
    show: true,
    description: 'stepFeaturesSDM120',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_DDS2382',
    value: false,
    show: true,
    description: 'stepFeaturesDDS2382',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_SDM630',
    value: false,
    show: true,
    description: 'stepFeaturesSDM630',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_DDSU666',
    value: false,
    show: true,
    description: 'stepFeaturesDDSU666',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_SOLAX_X1',
    value: false,
    show: true,
    description: 'stepFeaturesSOLAX_X1',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_LE01MR',
    value: false,
    show: true,
    description: 'stepFeaturesLE01MR',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_BL0940',
    value: false,
    show: true,
    description: 'stepFeaturesBL0940',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_TELEINFO',
    value: false,
    show: true,
    description: 'stepFeaturesTELEINFO',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_IEM3000',
    value: false,
    show: true,
    description: 'stepFeaturesIEM3000',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
  {
    name: 'USE_WE517',
    value: false,
    show: true,
    description: 'stepFeaturesWE517',
    include: ['USE_I2C', 'USE_ENERGY_SENSOR'],
    boards: ['all'],
    type: 'energy',
  },
];

export default energySensors;
