const lightSensors = [
   {
    name: 'USE_BH1750',
    value: false,
    show: true,
    description: 'stepFeaturesBH1750',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'light',
  },
  {
    name: 'USE_VEML6070',
    value: false,
    show: true,
    description: 'stepFeaturesVEML6070',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'light',
  },
  {
    name: 'USE_TSL2561',
    value: false,
    show: true,
    description: 'stepFeaturesTSL2561',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'light',
  },
  {
    name: 'USE_SI1145',
    value: false,
    show: true,
    description: 'stepFeaturesSI1145',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'light',
  },
  {
    name: 'USE_APDS9960',
    value: false,
    show: true,
    description: 'stepFeaturesAPDS9960',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'light',
  },
  {
    name: 'USE_VEML6075',
    value: false,
    show: true,
    description: 'stepFeaturesVEML6075',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'light',
  },
  {
    name: 'USE_MAX44009',
    value: false,
    show: true,
    description: 'stepFeaturesMAX44009',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'light',
  },
  {
    name: 'USE_TSL2591',
    value: false,
    show: true,
    description: 'stepFeaturesTSL2591',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'light',
  },
  {
    name: 'USE_AS3935',
    value: false,
    show: true,
    description: 'stepFeaturesAS3935',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'light',
  },
  {
    name: 'USE_VEML7700',
    value: false,
    show: true,
    description: 'stepFeaturesVEML7700',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'light',
  },
];

export default lightSensors;
