const temphumpressSensors = [
  {
    name: 'USE_SONOFF_SC',
    value: false,
    show: true,
    description: 'stepFeaturesSONOFF_SC',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_DS18x20',
    value: false,
    show: true,
    description: 'stepFeaturesDS18x20',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_DHT',
    value: false,
    show: true,
    description: 'stepFeaturesDHT',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_SHT',
    value: false,
    show: true,
    description: 'stepFeaturesSHT',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_HTU',
    value: false,
    show: true,
    description: 'stepFeaturesHTU',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_BMP',
    value: false,
    show: true,
    description: 'stepFeaturesBMP',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_SHT3X',
    value: false,
    show: true,
    description: 'stepFeaturesSHT3X',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_LM75AD',
    value: false,
    show: true,
    description: 'stepFeaturesLM75AD',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_AZ7798',
    value: false,
    show: true,
    description: 'stepFeaturesAZ7798',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_MAX31855',
    value: false,
    show: true,
    description: 'stepFeaturesMAX31855',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_MLX90614',
    value: false,
    show: true,
    description: 'stepFeaturesMLX90614',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_MAX31865',
    value: false,
    show: true,
    description: 'stepFeaturesMAX31865',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_HIH6',
    value: false,
    show: true,
    description: 'stepFeaturesHIH6',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_DHT12',
    value: false,
    show: true,
    description: 'stepFeaturesDHT12',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_DS1624',
    value: false,
    show: true,
    description: 'stepFeaturesDS1624',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_AHT1x',
    value: false,
    show: true,
    description: 'stepFeaturesAHT1x',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_HDC1080',
    value: false,
    show: true,
    description: 'stepFeaturesHDC1080',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_MCP9808',
    value: false,
    show: true,
    description: 'stepFeaturesMCP9808',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_HP303B',
    value: false,
    show: true,
    description: 'stepFeaturesHP303B',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
  {
    name: 'USE_LMT01',
    value: false,
    show: true,
    description: 'stepFeaturesLMT01',
    include: ['USE_I2C'],
    boards: ['all'],
    type: 'temphumpress',
  },
];

export default temphumpressSensors;
